source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SJLiveShow' do
pod 'AFNetworking', '~> 3.0'
pod 'YYModel'
pod 'SDWebImage'
pod 'LFLiveKit'
pod 'Socket.IO-Client-Swift', '~> 8.3.3'
pod 'Masonry'
end
